


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admins" (
    "admin_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."admins" OWNER TO "postgres";


ALTER TABLE "public"."admins" ALTER COLUMN "admin_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admins_admin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "booking_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trip_id" bigint NOT NULL,
    "passenger_id" bigint NOT NULL,
    "fare" double precision NOT NULL,
    "seat_no" smallint NOT NULL,
    "start_location" "text" NOT NULL,
    "end_location" "text" NOT NULL,
    "start_at" timestamp with time zone NOT NULL,
    "status" "text" NOT NULL
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


ALTER TABLE "public"."bookings" ALTER COLUMN "booking_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookings_booking_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trips" (
    "trip_id" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "route_id" bigint NOT NULL,
    "departure_at" timestamp with time zone NOT NULL,
    "arrival_at" timestamp with time zone NOT NULL,
    "bus_id" bigint NOT NULL,
    "driver_id" bigint NOT NULL,
    "is_reverse_trip" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."trips" OWNER TO "postgres";


ALTER TABLE "public"."trips" ALTER COLUMN "trip_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bus_schedules_schedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bus_type" (
    "type_id" smallint NOT NULL,
    "name" "text" NOT NULL,
    "capacity" smallint NOT NULL,
    "seat_template" "jsonb" NOT NULL
);


ALTER TABLE "public"."bus_type" OWNER TO "postgres";


ALTER TABLE "public"."bus_type" ALTER COLUMN "type_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bus_type_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."buses" (
    "bus_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "plate_no" "text" NOT NULL,
    "route" bigint,
    "bus_type" smallint NOT NULL,
    "owner" bigint NOT NULL,
    "status" "text" NOT NULL
);


ALTER TABLE "public"."buses" OWNER TO "postgres";


ALTER TABLE "public"."buses" ALTER COLUMN "bus_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."buses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."driver_shifts" (
    "shift_id" bigint NOT NULL,
    "driver_id" bigint NOT NULL,
    "shift_start" timestamp with time zone DEFAULT "now"() NOT NULL,
    "shift_end" timestamp with time zone
);


ALTER TABLE "public"."driver_shifts" OWNER TO "postgres";


ALTER TABLE "public"."driver_shifts" ALTER COLUMN "shift_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."driver_shifts_shift_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."drivers" (
    "driver_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "license" "text" NOT NULL,
    "status" "text" DEFAULT 'Active'::"text" NOT NULL,
    "assigned_bus" bigint,
    "employed_by" bigint
);


ALTER TABLE "public"."drivers" OWNER TO "postgres";


ALTER TABLE "public"."drivers" ALTER COLUMN "driver_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."drivers_driver_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."owners" (
    "owner_id" bigint NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."owners" OWNER TO "postgres";


ALTER TABLE "public"."owners" ALTER COLUMN "owner_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."owners_owner_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."passengers" (
    "passenger_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "wallet_id" bigint
);


ALTER TABLE "public"."passengers" OWNER TO "postgres";


ALTER TABLE "public"."passengers" ALTER COLUMN "passenger_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."passengers_passenger_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."routes" (
    "route_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "start" "text" NOT NULL,
    "end" "text" NOT NULL,
    "stops" "jsonb" NOT NULL,
    "status" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."routes" OWNER TO "postgres";


ALTER TABLE "public"."routes" ALTER COLUMN "route_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."route_route_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "contact_no" "text" NOT NULL,
    "email" "text" NOT NULL,
    "role" "text" DEFAULT '''Passenger''::text'::"text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON COLUMN "public"."users"."role" IS 'If NULL the user has been soft deleted';



ALTER TABLE "public"."users" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."wallets" (
    "wallet_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "balance" double precision DEFAULT '0'::double precision NOT NULL,
    "last_updated" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."wallets" OWNER TO "postgres";


ALTER TABLE "public"."wallets" ALTER COLUMN "wallet_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."wallets_wallet_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("admin_id");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("booking_id");



ALTER TABLE ONLY "public"."trips"
    ADD CONSTRAINT "bus_schedules_pkey" PRIMARY KEY ("trip_id");



ALTER TABLE ONLY "public"."bus_type"
    ADD CONSTRAINT "bus_type_pkey" PRIMARY KEY ("type_id");



ALTER TABLE ONLY "public"."buses"
    ADD CONSTRAINT "buses_pkey" PRIMARY KEY ("bus_id");



ALTER TABLE ONLY "public"."buses"
    ADD CONSTRAINT "buses_plate_no_key" UNIQUE ("plate_no");



ALTER TABLE ONLY "public"."driver_shifts"
    ADD CONSTRAINT "driver_shifts_pkey" PRIMARY KEY ("shift_id");



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_license_key" UNIQUE ("license");



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_pkey" PRIMARY KEY ("driver_id");



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_pkey" PRIMARY KEY ("owner_id");



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."passengers"
    ADD CONSTRAINT "passengers_pkey" PRIMARY KEY ("passenger_id");



ALTER TABLE ONLY "public"."passengers"
    ADD CONSTRAINT "passengers_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."passengers"
    ADD CONSTRAINT "passengers_wallet_id_key" UNIQUE ("wallet_id");



ALTER TABLE ONLY "public"."routes"
    ADD CONSTRAINT "route_pkey" PRIMARY KEY ("route_id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "unique_trip_seat" UNIQUE ("trip_id", "seat_no");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."wallets"
    ADD CONSTRAINT "wallets_pkey" PRIMARY KEY ("wallet_id");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_passenger_id_fkey" FOREIGN KEY ("passenger_id") REFERENCES "public"."passengers"("passenger_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("trip_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."trips"
    ADD CONSTRAINT "bus_schedules_bus_id_fkey" FOREIGN KEY ("bus_id") REFERENCES "public"."buses"("bus_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."trips"
    ADD CONSTRAINT "bus_schedules_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."drivers"("driver_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."trips"
    ADD CONSTRAINT "bus_schedules_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes"("route_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."buses"
    ADD CONSTRAINT "buses_bus_type_fkey" FOREIGN KEY ("bus_type") REFERENCES "public"."bus_type"("type_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."buses"
    ADD CONSTRAINT "buses_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."owners"("owner_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."buses"
    ADD CONSTRAINT "buses_route_fkey" FOREIGN KEY ("route") REFERENCES "public"."routes"("route_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."driver_shifts"
    ADD CONSTRAINT "driver_shifts_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "public"."drivers"("driver_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_assigned_bus_fkey" FOREIGN KEY ("assigned_bus") REFERENCES "public"."buses"("bus_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_employed_by_fkey" FOREIGN KEY ("employed_by") REFERENCES "public"."owners"("owner_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."passengers"
    ADD CONSTRAINT "passengers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."passengers"
    ADD CONSTRAINT "passengers_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallets"("wallet_id") ON UPDATE CASCADE ON DELETE SET NULL;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."admins" TO "anon";
GRANT ALL ON TABLE "public"."admins" TO "authenticated";
GRANT ALL ON TABLE "public"."admins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admins_admin_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bookings_booking_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bookings_booking_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bookings_booking_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trips" TO "anon";
GRANT ALL ON TABLE "public"."trips" TO "authenticated";
GRANT ALL ON TABLE "public"."trips" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bus_schedules_schedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bus_schedules_schedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bus_schedules_schedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bus_type" TO "anon";
GRANT ALL ON TABLE "public"."bus_type" TO "authenticated";
GRANT ALL ON TABLE "public"."bus_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bus_type_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bus_type_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bus_type_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."buses" TO "anon";
GRANT ALL ON TABLE "public"."buses" TO "authenticated";
GRANT ALL ON TABLE "public"."buses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."buses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."buses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."buses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."driver_shifts" TO "anon";
GRANT ALL ON TABLE "public"."driver_shifts" TO "authenticated";
GRANT ALL ON TABLE "public"."driver_shifts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."driver_shifts_shift_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."driver_shifts_shift_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."driver_shifts_shift_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."drivers" TO "anon";
GRANT ALL ON TABLE "public"."drivers" TO "authenticated";
GRANT ALL ON TABLE "public"."drivers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."drivers_driver_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."drivers_driver_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."drivers_driver_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."owners" TO "anon";
GRANT ALL ON TABLE "public"."owners" TO "authenticated";
GRANT ALL ON TABLE "public"."owners" TO "service_role";



GRANT ALL ON SEQUENCE "public"."owners_owner_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."owners_owner_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."owners_owner_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."passengers" TO "anon";
GRANT ALL ON TABLE "public"."passengers" TO "authenticated";
GRANT ALL ON TABLE "public"."passengers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."passengers_passenger_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."passengers_passenger_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."passengers_passenger_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."routes" TO "anon";
GRANT ALL ON TABLE "public"."routes" TO "authenticated";
GRANT ALL ON TABLE "public"."routes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."route_route_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."route_route_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."route_route_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."wallets" TO "anon";
GRANT ALL ON TABLE "public"."wallets" TO "authenticated";
GRANT ALL ON TABLE "public"."wallets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."wallets_wallet_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."wallets_wallet_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."wallets_wallet_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


