CREATE TABLE IF NOT EXISTS "public"."stripe_topup_payments" (
    "payment_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "passenger_id" bigint NOT NULL,
    "wallet_id" bigint NOT NULL,
    "amount" numeric(12, 2) NOT NULL,
    "currency" text DEFAULT 'lkr'::text NOT NULL,
    "status" text DEFAULT 'pending'::text NOT NULL,
    "stripe_checkout_session_id" text,
    "stripe_payment_intent_id" text,
    "stripe_event_id" text,
    "checkout_url" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "completed_at" timestamp with time zone,
    "last_updated" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "stripe_topup_payments_amount_check" CHECK (("amount" > 0)),
    CONSTRAINT "stripe_topup_payments_status_check" CHECK (("status" = ANY (ARRAY[
        'pending'::text,
        'completed'::text,
        'failed'::text,
        'expired'::text,
        'failed_to_create_checkout'::text
    ])))
);

ALTER TABLE ONLY "public"."stripe_topup_payments"
    ADD CONSTRAINT "stripe_topup_payments_pkey" PRIMARY KEY ("payment_id");

ALTER TABLE ONLY "public"."stripe_topup_payments"
    ADD CONSTRAINT "stripe_topup_payments_checkout_session_key" UNIQUE ("stripe_checkout_session_id");

ALTER TABLE ONLY "public"."stripe_topup_payments"
    ADD CONSTRAINT "stripe_topup_payments_event_key" UNIQUE ("stripe_event_id");

ALTER TABLE ONLY "public"."stripe_topup_payments"
    ADD CONSTRAINT "stripe_topup_payments_passenger_id_fkey"
    FOREIGN KEY ("passenger_id") REFERENCES "public"."passengers"("passenger_id")
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."stripe_topup_payments"
    ADD CONSTRAINT "stripe_topup_payments_wallet_id_fkey"
    FOREIGN KEY ("wallet_id") REFERENCES "public"."wallets"("wallet_id")
    ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS "stripe_topup_payments_passenger_id_idx"
    ON "public"."stripe_topup_payments" USING btree ("passenger_id");

CREATE INDEX IF NOT EXISTS "stripe_topup_payments_wallet_id_idx"
    ON "public"."stripe_topup_payments" USING btree ("wallet_id");

CREATE OR REPLACE FUNCTION "public"."complete_stripe_topup"(
    "p_checkout_session_id" text,
    "p_payment_intent_id" text,
    "p_stripe_event_id" text
)
RETURNS TABLE (
    "payment_id" bigint,
    "wallet_id" bigint,
    "credited" boolean,
    "new_balance" double precision
)
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = "public"
AS $$
DECLARE
    topup_record "public"."stripe_topup_payments"%ROWTYPE;
    updated_balance double precision;
BEGIN
    SELECT *
    INTO topup_record
    FROM "public"."stripe_topup_payments"
    WHERE "stripe_checkout_session_id" = p_checkout_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Top-up payment not found for Stripe Checkout Session %', p_checkout_session_id;
    END IF;

    IF topup_record."status" = 'completed' THEN
        SELECT "balance"
        INTO updated_balance
        FROM "public"."wallets"
        WHERE "wallet_id" = topup_record."wallet_id";

        RETURN QUERY SELECT
            topup_record."payment_id",
            topup_record."wallet_id",
            false,
            updated_balance;
        RETURN;
    END IF;

    UPDATE "public"."wallets"
    SET
        "balance" = "balance" + topup_record."amount"::double precision,
        "last_updated" = now()
    WHERE "wallet_id" = topup_record."wallet_id"
    RETURNING "balance" INTO updated_balance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Wallet % was not found for top-up payment %',
            topup_record."wallet_id",
            topup_record."payment_id";
    END IF;

    UPDATE "public"."stripe_topup_payments"
    SET
        "status" = 'completed',
        "stripe_payment_intent_id" = COALESCE(p_payment_intent_id, "stripe_payment_intent_id"),
        "stripe_event_id" = COALESCE(p_stripe_event_id, "stripe_event_id"),
        "completed_at" = now(),
        "last_updated" = now()
    WHERE "payment_id" = topup_record."payment_id";

    RETURN QUERY SELECT
        topup_record."payment_id",
        topup_record."wallet_id",
        true,
        updated_balance;
END;
$$;

GRANT SELECT, INSERT, UPDATE ON TABLE "public"."stripe_topup_payments" TO "service_role";
GRANT USAGE, SELECT ON SEQUENCE "public"."stripe_topup_payments_payment_id_seq" TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."complete_stripe_topup"(text, text, text) TO "service_role";
